### PR TITLE
Adds a plugins view

### PR DESCRIPTION
**Pull request by mswaidan**
Thought we could use a way to navigate to plugins from within SpeckleAdmin.
Which leads me to another thought: could we treat some plugins as routes within SpeckleAdmin? Goal would be the ability to drop in certain plugins as modules in order to use them within the SpeckleAdmin interface... 🤔

### CODE REVIEW

**Comment by didimitrie** [comment]
Looks good, and I will merge. Though I'm actually considering deprecating the plugin architecture as it's a nightmare to maintain things up to date on multiple servers.

We will have this discussion later, for now this is perfect!

**Comment by daviddekoning** [comment]
@didimitrie, could we update the architecture/install script so that plugins don’t need to be reinstalled after a main server upgrade? It won’t help for breaking changes, but might reduce some of the pain, while still keeping the benefits of plugins

**Comment by didimitrie** [comment]
> @didimitrie, could we update the architecture/install script so that plugins don’t need to be reinstalled after a main server upgrade? It won’t help for breaking changes, but might reduce some of the pain, while still keeping the benefits of plugins

They don't need to be reinstalled after a server upgrade! unless i'm missing something

**Comment by daviddekoning** [comment]
Never mind, then! I got that impression from our server guy...

**Pull request merged**
