### PR TITLE
Adds basic dynamic component registration

### PR DESCRIPTION
**Pull request by mswaidan**
This branch automatically registers components that live in the `./src/plugins/` folder. See the `README.md` in that folder for details on naming conventions.

Example VERY basic component for testing, should be named `plugin-A.vue`:
```
<template>
  <div>Hi, {{$store.state.user.name}}. Welcome to Plugin A</div>
</template>
<script>
export default {
  name: 'PluginA',
  created(){
    console.log('Plugin A created!')
  }

}
</script>
```

### CODE REVIEW

**Comment by didimitrie** [comment]
Okay, this looks good and i think the principle's sound. To reiterate: 
- people want to create their own custom plugins, and don't want to share stuff sometimes
- it's a hassle to maintain a private fork with the custom routes always, so we can register these dynamically
- it works, as if you do `npm run build` they will be incorporated in the app

Trying now to give it a spin!

**Comment by didimitrie** [comment]
Just did some things:

Changed base component template to:

```vue
<template>
  <div class='display-1 ma-5 pa-5'>Hi, {{$store.state.user.name}}. Welcome to Plugin B</div>
</template>
<script>
export default {
  name: 'PluginB',
  manifest: {
    humanReadableName: "Plugin B",
    description: "Something witty.",
    requireAuth: false,
    icon: "flight_land", // from: https://material.io/resources/icons/
    registerInNav: true
  },
  created( ) {
    console.log( 'Plugin A created!' )
  }
}
</script>
```

And added navbar routes to each plugin, if detected. 

A todo: check against the plugin manifest wether isAuthRequired, and if so, do not  display them in the navbar!

**Comment by didimitrie** [comment]
forgot to enforce the icon prop in plugin navbar. 

image

@mswaidan, if you're happy, i'm happy with how this looks like!

**Comment by mswaidan** [comment]
Perfect, navbar was next on my list. Thanks! Will take a crack at docs
today if I have a few mins.

**Pull request merged**
